[project]
name = "qt-hello"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "pyqt6==6.4.2",
    "pyqt6-qt6==6.4.3",
    "pyqt6-sip==13.10.2",
    "pyqt6-tools==6.4.2.3.3",
    "setuptools>=80.9.0",
]
